### PR TITLE
Updated commands.json to the version of 200160226

### PR DESCRIPTION
**Pull request by qrilka**
As it's a quite a heavy patch I think we'll need to review it thoroughly
Also I see what could be improved (some commands could easily be fully supported e.g.)
And for sure we'll need a major version bump for this.

### CODE REVIEW

**Comment by Thooms** [comment]
Perhaps it could be wise to write in the same time the unit tests for everything? That way when the big change comes (I understand @informatikr wanted to go for a full handwritten API instead of generated code), we can go more smoothly?
I can review the patch this week and write the unittests if @informatikr or @k-bx are willing to merge afterwards :)

**Comment by k-bx** [comment]
@Thooms this would be highly appreciated. On my side, I started checking this PR against my work-project to make sure at least basic stuff works on tests/staging (maybe even prod for load-testing, but we'll see).

**Comment by Thooms** [comment]
OK, I'm on it then. I'll try to write as much unittests as I can, let's see afterwards for the rest!

**Comment by qrilka** [comment]
that sounds good @Thooms - do you want to put those unittests into this PR?

**Comment by Thooms** [comment]
@qrilka I would prefer starting a new branch (since we're not only talking about updating the API anymore), and cherry-picking your commit into it, if you're okay with that.

**Comment by qrilka** [comment]
Sure, other option is to merge this one and unittests as another PR and not do any releases until we have good coverage.
But @k-bx is the maintainer of this package

**Comment by k-bx** [comment]
I think cherry-picking should provide a good way to have these PRs separately implemented, but once Thooms's is ready, I can merge this one and Thooms's then, should work well.

**Comment by Thooms** [comment]
Hello there, just a small message to signal I'm still working on the testsuite. There a lot of code to write, and I can't commit for now, but I'll make a PR as soon as it's showable :)

**Comment by Thooms** [comment]
-> #61

**Comment by qrilka** [comment]
Updated (actually rebased) according to #62 - it appears that Redis lists even commands from unstable version and they don't have `"since"` set.
@Thooms I suppose you'll need to rebase you work unfortunately

**Comment by Thooms** [comment]
Will do, no problem!

**Comment by k-bx** [comment]
I've merged this branch into [commands-20160226](https://github.com/informatikr/hedis/tree/commands-20160226) branch in the main hedis repo, thank you! Let's continue working on top of that one everyone.

**Pull request closed without merging**
