### PR TITLE
Add spopN

### PR DESCRIPTION
**Pull request by MichaelXavier**
This has been available in redis since 3.2 and is quite handy so I
thought I'd add it.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Had to upgrade the redis version to support spopN. Alternatively, I could go down the road of adding a redis version dimension to the build matrix but then I'd have to support expected failures by redis version in the test suite so I left that alone.

**Comment by MichaelXavier** [comment]
@k-bx Hate to be a bother, but I'd like to bump this and #102. I've got some functionality I need to write that would would be much simpler if this functionality was exposed.

**Comment by k-bx** [comment]
@MichaelXavier no bother at all, thanks for doing the work, I'll address both things today

**Comment by k-bx** [comment]
Released under 0.10.0, thank you!

**Pull request merged**
