### PR TITLE
Add XGROUP CREATE MKSTREAM support

### PR DESCRIPTION
**Pull request by j1r1k**

### CODE REVIEW

**Comment by domenkozar** [comment]
@informatikr we're using this, any chance of merging?

**Comment by ysangkok** [comment]
I believe @aravindgopall is now maintaining this, so tagging him instead.

**Comment by qnikst** [comment]
Hello, we have pulled a bit different version that also supports optional `ENTRIESREAD` argument. Please check if upstream version works for you and if not I'll be ready to fix that.

**Comment by qnikst** [comment]
Closing this MR, if upstream version does not work for you please ping me!

**Pull request closed without merging**
