### PR TITLE
Make withConnect friendly to transformer stack

### PR DESCRIPTION
**Pull request by TomMD**
withConnect has an embedded IO (i.e. `-> (a -> IO b) ->`) which is famously annoying for monad stacks.  We can generalize this really easily though using MonadMask from the exceptions package and lifting the connect/disconnect calls.

### CODE REVIEW

**Comment by k-bx** [comment]
@TomMD thanks! I wonder, what was the reason to add the doctest constraint? The code is building fine on GHC 8.4 for me via `stack build --stack-yaml ./stack-8.4.yaml` without that constraint, but fails for 8.4 and older as can be seen [in Travis](https://travis-ci.org/github/informatikr/hedis/builds/665254161?utm_source=github_status) , so I wonder what's the reason there. Thanks!

p.s.: I don't really use the `run-tests` script, neither our Travis configuration, I wonder if we should just remove it.

**Comment by TomMD** [comment]
I could remove that constraint if you desire.  It was rather unmotivated.

**Comment by k-bx** [comment]
Please do, it'd fix older GHC versions.

**Comment by k-bx** [comment]
Thanks, uploaded as 0.12.12

**Pull request merged**
