### PR TITLE
Scan commands

### PR DESCRIPTION
**Pull request by qrilka**
Branch is based on #52 
It's based and fixes #22 - thanks @vipo

### CODE REVIEW

**Comment by qrilka** [comment]
Other idea is to add a newtype `Cursor` to make the interface a bit more typesafe

**Comment by vipo** [comment]
Sure, having a Cursor is a much better idea.

**Comment by qrilka** [comment]
with a newtype it looks nicer :)

**Comment by qrilka** [comment]
Rebased

**Comment by qrilka** [comment]
Merged in #67

**Pull request closed without merging**
