### PR TITLE
Replace list inputs with NonEmpty

### PR DESCRIPTION
**Pull request by jxv**
Will break API

### CODE REVIEW

**Comment by jxv** [comment]
Fixes #44

**Comment by jxv** [comment]
flaky tests

**Comment by jxv** [comment]
That one test is still failing. `STACK_YAML=stack-head.yaml stack test` _works on my machine_.

**Comment by jxv** [comment]
bump

**Comment by qrilka** [comment]
@jxv I think there is at least 1 thing missing in this PR - update to `GenCmds.hs`, i.e. if commands will be updated with it your changes will get overwritten back

**Comment by k-bx** [comment]
@jxv please update `GenCmds.hs` and I'll test new version on our project to estimate amount of pain typical project would receive because of this breakage. I'd then be able to understand if this is a good idea or not.

**Comment by Ericson2314** [comment]
So what happened here? I just realized lost a day to not having this.

**Comment by jxv** [comment]
@Ericson2314 I spent a surprisingly amount of time trying to modify `GenCmd.hs` as suggested. As it became clearer what was needed for `GenCmd.hs`, redis or something similar wasn't really needed for my project. None of it was worth the effort. Although I'm still not sure why a code generator is needed for this project, it seems excessive. Perhaps, there's a good reason?

**Comment by Ericson2314** [comment]
Did you get anywhere? If you could push even a WIP thing I'd pick it up.

**Comment by jxv** [comment]
Nope. I would have needed to start over.

**Comment by k-bx** [comment]
I am ok to ditch the code generator, btw. At least not seeing a big reason to keep it. If somebody wants to try the non-codegen approach -- go ahead.

A warning -- I am definitely not keen to break people's current code, so whatever the approach , we will need to make sure that the transition to the new API will be smooth.

**Pull request closed without merging**
