### PR TITLE
Ready for review: Clustering Implementation - continuation

### PR DESCRIPTION
**Pull request by jwoudenberg**
This is a continuation of @alexjg's work in #142. It contains some bug fixes, passes all tests, and is up to date with this repo's master.

### CODE REVIEW

**Comment by jwoudenberg** [comment]
One remaining question is how redirects should be handled in the case of a `MULTI .. EXEC` block. This might need some research, I don't know what the Redis server will even do if a transaction comes for a hashslot of which some of the keys are currently migrating. Maybe the code in [RedisLab/redis-client-proxy](https://github.com/RedisLabs/redis-cluster-proxy/blob/f8dc227a07f4a738b5fd211501bd521f32f1fcbd/COMMANDS.md) will provide some pointers.

**Comment by jwoudenberg** [comment]
This is now ready for review!

**Comment by jwoudenberg** [comment]
CI is now passing as well!

**Comment by k-bx** [comment]
Thank you very much for the work! Released as 0.14.0

**Pull request merged**
